Repository cczapatat/isoftapps-moviles-misw4203, pull requests merged in 2024-04, with the labels that each got.

#66 [HU01-02] Ajustes de Navegación
  app/src/main/java/miso4203/mobile/app/vinilos/MainActivity.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/AlbumsAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/PerformerAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/TrackAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album/AlbumFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_detail/AlbumDetailFragment.kt
  app/src/main/res/drawable/baseline_headphones_24.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_album_detail.xml
  app/src/main/res/values/strings.xml
Labels: HU

#67 HU01 Albumnes filtrados - Pair Programming
  app/src/main/java/miso4203/mobile/app/vinilos/LoginActivity.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/AlbumsAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/PerformerAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/TrackAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album/AlbumFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album/AlbumViewModel.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_detail/AlbumDetailFragment.kt
  app/src/main/res/drawable/searchview_backgound.xml
  app/src/main/res/layout/header_menu.xml
Labels: HU

#68 add espresso test for view album list
  app/src/androidTest/java/miso4203/mobile/app/vinilos/ExampleInstrumentedTest.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/LoginActivityTest.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/LoginViewAlbumListTest.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/MainActivityTest.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/MainActivityTest2.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/MainActivityTest3.kt
Labels: Task

#70 [HU-01] add espresso test for success filtered album list
  app/src/androidTest/java/miso4203/mobile/app/vinilos/LoginViewAlbumListSuccessFilteredTest.kt
Labels: Task

#73 Pruebas Expresso Ver albumnes, filtrar, lista vacia, seleccionar un item
  app/src/androidTest/java/miso4203/mobile/app/vinilos/LoginAlbumsFilterNotExistsAny.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/LoginListAlbumsFilterSelectOneAndReturn.kt
Labels: Test
