Repository cczapatat/isoftapps-moviles-misw4203, pull requests merged in 2024-05, with the labels that each got.

#76 [HU04] Listar los artistas
  app/build.gradle.kts
  app/src/main/java/miso4203/mobile/app/vinilos/MainActivity.kt
  app/src/main/java/miso4203/mobile/app/vinilos/models/Artist.kt
  app/src/main/java/miso4203/mobile/app/vinilos/network/NetworkServiceAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/repositories/AlbumDetailRepository.kt
  app/src/main/java/miso4203/mobile/app/vinilos/repositories/AlbumRepository.kt
  app/src/main/java/miso4203/mobile/app/vinilos/repositories/ArtistRepository.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/AlbumsAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/ArtistsAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album/AlbumFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album/AlbumViewModel.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_detail/AlbumDetailFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_detail/AlbumDetailViewModel.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/artist/ArtistFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/artist/ArtistViewModel.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/collector/CollectorFragment.kt
  app/src/main/res/layout/artist_item.xml
  app/src/main/res/layout/fragment_album.xml
  app/src/main/res/layout/fragment_artist.xml
Labels: HU, Task

#85 [HU04] Micro-Optimizaciones (Pair Programming)
  app/src/main/java/miso4203/mobile/app/vinilos/cache/PicassoWrapper.kt
  app/src/main/java/miso4203/mobile/app/vinilos/models/Album.kt
  app/src/main/java/miso4203/mobile/app/vinilos/models/AlbumDetail.kt
  app/src/main/java/miso4203/mobile/app/vinilos/models/Artist.kt
  app/src/main/java/miso4203/mobile/app/vinilos/models/ArtistDetail.kt
  app/src/main/java/miso4203/mobile/app/vinilos/models/Performer.kt
  app/src/main/java/miso4203/mobile/app/vinilos/network/NetworkServiceAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/AlbumsAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/ArtistsAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/PerformerAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_create/AlbumCreateFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_detail/AlbumDetailFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/artist_detail/ArtistDetailFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/collector/CollectorFragment.kt
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/artist_item.xml
  app/src/main/res/layout/fragment_artist_detail.xml
  app/src/main/res/layout/performer_item.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: Task

#87 Fix to Lists
  app/src/main/res/layout/fragment_album.xml
  app/src/main/res/layout/fragment_artist.xml
Labels: BUG

#91 add microoptimizations based on code inspection with Lint
  app/src/androidTest/java/miso4203/mobile/app/vinilos/CreateAlbumSucessTestOne.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/Express_test_8_d.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/Expresso_test_4_d.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/LoginAlbumsFilterNotExistsAny.kt
  app/src/androidTest/java/miso4203/mobile/app/vinilos/LoginViewAlbumListSuccessFilteredTest.kt
  app/src/main/java/miso4203/mobile/app/vinilos/database/dao/ArtistDao.kt
  app/src/main/java/miso4203/mobile/app/vinilos/network/CacheManager.kt
  app/src/main/java/miso4203/mobile/app/vinilos/network/NetworkServiceAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/repositories/ArtistDetailRepository.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/AlbumsAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/ArtistsAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album/AlbumViewModel.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_create/AlbumCreateFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_create/AlbumCreateViewModel.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_detail/AlbumDetailFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/artist/ArtistViewModel.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/artist_detail/ArtistDetailViewModel.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/collector/CollectorFragment.kt
  app/src/main/res/drawable/add_x.xml
  app/src/main/res/drawable/gradient_overlay.xml
  app/src/main/res/drawable/item_selector.xml
  app/src/main/res/drawable/rounded_shape.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/content_main.xml
  app/src/main/res/layout/fragment_artist_detail.xml
  app/src/main/res/layout/header_menu.xml
  app/src/main/res/layout/lateral_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: Task

#97 HU08 Add Track to album
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/miso4203/mobile/app/vinilos/models/Album.kt
  app/src/main/java/miso4203/mobile/app/vinilos/network/NetworkServiceAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/repositories/AlbumRepository.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/adapters/CollectorAlbumsAdapter.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/collector_detail/CollectorDetailFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/track_add/TrackAddFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/track_add/TrackAddViewModel.kt
  app/src/main/res/layout/fragment_album_create.xml
  app/src/main/res/layout/fragment_album_detail.xml
  app/src/main/res/layout/fragment_artist_detail.xml
  app/src/main/res/layout/fragment_collector_detail.xml
  app/src/main/res/layout/fragment_track_add.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: Task

#98 HU08 Hide Btns when It is not collector
  app/src/main/java/miso4203/mobile/app/vinilos/MainActivity.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_detail/AlbumDetailFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/collector_detail/CollectorDetailFragment.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/track_add/TrackAddFragment.kt
  app/src/main/res/layout/fragment_album_detail.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: Task

#105 Fix, Accesesibility Lint Android
  app/src/main/java/miso4203/mobile/app/vinilos/ui/album_create/AlbumCreateFragment.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/artist_item.xml
  app/src/main/res/layout/lateral_menu.xml
  app/src/main/res/values/strings.xml
Labels: Task

#108 improve accesibility for artist module
  app/src/androidTest/java/miso4203/mobile/app/vinilos/VisitorLoginViewCollectorSelectOneSuccessData.kt
  app/src/main/java/miso4203/mobile/app/vinilos/database/dao/CollectorDao.kt
  app/src/main/java/miso4203/mobile/app/vinilos/ui/artist_detail/ArtistDetailFragment.kt
  app/src/main/res/layout/fragment_artist_detail.xml
  app/src/main/res/layout/header_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Task
